import { Metadata } from "next"
import "../../../globals.css"
import { genInt } from "@/app/_lib/generateRandomInteger"

export const metadata: Metadata = {
  title: {
    default: "NextCraft - Hasan.Dev",    // Title for paths that dont specify their own titles
    template: "%s | Hasan.Dev",   // For child routes when u want to apply prefix / suffix to a route mostly used for multipage routing
  },
  description: 'Generated by Next.js',
}


export default function ProductLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const number = genInt(2)
  if (number < 1) {
    throw new Error("intentional error");
  }

  return (
    <html lang="en">
      <body>
        <header style={{ padding: "10px", backgroundColor: "lightgray", width: "full", textAlign: "center", borderRadius: "5px" }}>HEADER</header>
        {children}
        <footer style={{ padding: "10px", backgroundColor: "lightgray", width: "full", textAlign: "center", borderRadius: "5px" }}>FOOTER</footer>
      </body>
    </html>
  )
}
