export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "10px", backgroundColor: "lightgray", width: "full", textAlign: "center", borderRadius: "5px" }}>HEADER</header>
        {children}
        <footer style={{ padding: "10px", backgroundColor: "lightgray", width: "full", textAlign: "center", borderRadius: "5px" }}>FOOTER</footer>
      </body>
    </html>
  )
}
