'use client'
import { usePathname } from "next/navigation"
import Link from "next/link"
import "../globals.css"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const navlinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forgotPassword" }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body>
        <header>
          {
            navlinks.map((link) => (
              <p><Link href={link.href} className={`font-bold ${pathname === link.href ? 'text-red-400' : 'text-blue-400'}`}>{link.name}</Link></p>
            ))
          }
        </header>
        {children}
        <p className="font-bold text-gray-500 hover:text-gray-800">Current route : {pathname}</p>

      </body>
    </html>
  )
}
